site_name: OSU Extension Website Documentation

repo_url: https://github.com/osu-eesc/cms-docs
edit_uri: edit/master/user-guide/docs
site_description: 'OSU Extension Web-guide'
theme:
  name: readthedocs
extra_css:
  - css/extra.css
nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - Introduction: intro.md
  - Using the Extension Website: using-site.md
  - Getting Started: getting-started.md
  - Adding and Editing Content: adding-editing.md
  - Managing Content: managing-content.md
  - Content Requirements and Best Practices: content-requirements.md
  - Getting Help: getting-help.md
  - Instructions for Special User Roles: special-roles.md
  - Glossary: glossary.md
  - Update Log: update-log.md
