site_name: OSU Extension Website User Guide

site_description: 'OSU Extension Web-guide'
theme:
  name: readthedocs
extra_css:
  - css/extra.css
google_analytics: ['UA-109218015-4', 'osu-eesc.github.io']
site_favicon: favicon.ico
nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - How-to Videos: how-to-videos.md
  - Introduction: intro.md
  - Using the Extension Website: using-site.md
  - Getting Started with Content: getting-started.md
  - Adding and Editing Content:
      - General Concepts: content-types/index.md
      - Announcement: content-types/announcement.md
      - Article: content-types/article.md
      - Collection: content-types/collection.md
      - County Office: content-types/county-office.md
      - Educational Document: content-types/educational-document.md
      - Event: content-types/event.md
      - Focus Area: content-types/focus-area.md
      - Newsletter: content-types/newsletter.md
      - Online Resource: content-types/online-resource.md
      - Program: content-types/program.md
      - Program Resource: content-types/program-resource.md
      - Project: content-types/project.md
      - Project Material: content-types/project-material.md
      - Subpage: content-types/subpage.md
      - Topic Page: content-types/topic.md
      - User Profile: content-types/user-profile.md
      - Video: content-types/video.md
  - Managing Content: managing-content.md
  - Content Requirements and Best Practices: content-requirements.md
  - Content Feedback and Analytics: feedback-analytics.md
  - Getting Help: getting-help.md
  - Instructions for Special User Roles: special-roles.md
  - Glossary Reference: glossary.md
  - Update Log: update-log.md
