site_name: OSU Extension Website Documentation

site_description: 'OSU Extension Web-guide'
theme:
  name: readthedocs
extra_css:
  - css/extra.css
google_analytics: ['UA-109218015-4', 'osu-eesc.github.io/cms-docs/user-guide/site/']
site_favicon: favicon.ico
nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - Introduction: intro.md
  - Using the Extension Website: using-site.md
  - Getting Started with Content: getting-started.md
  - How-to Videos: how-to-videos.md
  - Adding and Editing Content: adding-editing.md
  - Managing Content: managing-content.md
  - Content Requirements and Best Practices: content-requirements.md
  - Getting Help: getting-help.md
  - Instructions for Special User Roles: special-roles.md
  - Glossary Reference: glossary.md
  - Update Log: update-log.md
